name: Propuesta de charla
description: Usa esta plantilla para proponer una charla en nuestros meetups
title: T칤tulo de tu charla...
labels: [cfp]
assignees:
  - lupomontero
  - lizzie136
  - diananr
  - Xpktro
  - brunogonzales
body:
  - type: markdown
    attributes:
      value: |
        Nuestros eventos se rigen por el siguiente
        [C칩digo de conducta](http://es.confcodeofconduct.com/)

        Antes de proponer una charla, recuerda revisarlo para ver si estamos en
        la misma onda 游땕
  - type: dropdown
    id: talk-type
    attributes:
      label: 쯈u칠 tipo de presentaci칩n quieres hacer?
      options:
        - Keynote (20 a 30 minutos)
        - Lightning Talk (+- 5 minutos)
        - Avisos de trabajo / comunidades / actividades / etc
    validations:
      required: true
  - type: input
    id: name
    attributes:
      label: 쮺u치l es tu nombre?
    validations:
      required: true
  - type: textarea
    id: about
    attributes:
      label: Cu칠ntanos un poco sobre ti
      description: |
        Esto ser치 usado como tu Bio en redes sociales y para presentarte a los
        asistentes al meetup.
    validations:
      required: true
  - type: input
    id: talk-title
    attributes:
      label: 쮺u치l es el t칤tulo de tu charla?
      description: |
        La idea es que resuma la idea central de tu presentaci칩n. Algo como:

        - Closures v/s Clases, la batalla final
        - 10 Features de ES7 que tienes que conocer, (el numero 4 te dejar치 llorando)
        - Introducci칩n al desarrollo con ReactJS
    validations:
      required: true
  - type: textarea
    id: talk-description
    attributes:
      label: Danos una descripci칩n de tu charla (20 palabras)
  - type: textarea
    id: social
    attributes:
      label: 쯊ienes alguna red social donde podamos contactarte?
      description: Twitter / Facebook / Instagram / ...
    validations:
      required: true
  - type: input
    id: org
    attributes:
      label: Representas a alguna compa침칤a o empresa?
  - type: textarea
    id: extra-info
    attributes:
      label: 쯈uieres agregar algo m치s?
  - type: markdown
    attributes:
      value: |
        Cualquier pregunta no duden en consultar a lxs organizadores :wave:

        Muchas Gracias!
        El equipo de LimaJS
